# ❌ DISABLED - Deprecated Helm-based CI/CD Pipeline (Preserved for Reference Only)

name: ❌ DISABLED - CI/CD Pipeline with Helm Deployments

on:
  workflow_dispatch:  # Only manual trigger allowed

jobs:
  skip-job:
    runs-on: ubuntu-latest
    steps:
      - name: CI/CD is disabled
        run: echo "This workflow is intentionally disabled. Use Google Cloud Run pipeline instead."

